run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120

  goimports:
    local-prefixes: github.com/yuvalk/staticsocket

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  funlen:
    lines: 80
    statements: 40

  gosec:
    excludes:
      - G404 # Use of weak random number generator
      - G306 # Expect WriteFile permissions to be 0600 or less

  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
          - sayRepetitiveInsteadOfStutters

  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/yuvalk/staticsocket
          - gopkg.in/yaml.v3

linters:
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - gochecknoglobals
    - gocognit
    - godot
    - godox
    - err113
    - nestif
    - prealloc
    - testpackage
    - wsl

issues:
  exclude-dirs:
    - vendor
    - testdata
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - dupl
    - path: testdata/
      linters:
        - revive
        - stylecheck
        - gosec
    - linters:
        - lll
      source: "^//go:generate "

  exclude:
    # Allow shadowing of 'err'
    - 'shadow: declaration of "err" shadows declaration'
    # Allow long lines in tests
    - 'line is \d+ characters, out of \d+ allowed'

  max-issues-per-linter: 0
  max-same-issues: 0